### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by teamdodo** [Dogeek/isaac-debug-helper#2]
Which Creative Commons have you chosen?
CC-BY and CC-BY-SA-NC for example are really different. Also, why not use a software-specific license?

**Comment by sbordeyne** [comment]
I intended to change the license to LGPL-3 but I never did. As long as credit is given, all the  code can be modified or used as-is in commercial or open-source products. As long as a link to this git repo is given when distributing the software, I don't really care.

**Comment by teamdodo** [comment]
Thanks, practically is a CC-BY: just give credits.
